### ISSUE TITLE
Bug : revoke all privs. Tried /grantme all and the inventory got locked

### ISSUE THREAD

**Issue by Gobtous** [Salzar-R2D2/StaffRanks#2]
I think there is a conflit with a mod and i can't find which one. And when i use /grantme all, the inventory revert to the default one. Is it related to having several privs at once ?

And maybe we can merge it with this mod ?
https://content.minetest.net/packages/AiTechEye/servercleaner/

I just remplaced the default privs with the one from server cleaner.

**Comment by Elysian-dev** [comment]
Yes, I'll do a new update soon, so I don't need privileges anymore.
