### ISSUE TITLE
Don´t nil privs of other mods

### ISSUE THREAD

**Issue by blaboing** [Salzar-R2D2/StaffRanks#3]
You shouldn´t mess with other mods privs just for rank nametags
https://github.com/Salzar-R2D2/StaffRanks/blob/ecd40e160ac187bcfc1d211bbfc6cc85369a948e/init.lua#L27-L31

**Comment by appgurueu** [comment]
:skull:

**Comment by appgurueu** [comment]
Glad to see that you fixed this :+1:
